export const keys = [
  [
    {class: 'keys', keyname: 'Backquote', en: '`', enShift: '~', enCapsShift: '~', enCaps: '`', ru: 'ё', ruShift: 'Ё', ruCaps: 'Ё'},
    {class: 'keys', keyname: 'Digit1', en: '1', enShift: '!', enCapsShift: '!', enCaps: '1', ru: '1', ruShift: '!', ruCaps: '1'},
    {class: 'keys', keyname: 'Digit2', en: '2', enShift: '@', enCapsShift: '@', enCaps: '2', ru: '2', ruShift: '"', ruCaps: '2'},
    {class: 'keys', keyname: 'Digit3', en: '3', enShift: '#', enCapsShift: '#', enCaps: '3', ru: '3', ruShift: '№', ruCaps: '3'},
    {class: 'keys', keyname: 'Digit4', en: '4', enShift: '$', enCapsShift: '$', enCaps: '4', ru: '4', ruShift: ';', ruCaps: '4'},
    {class: 'keys', keyname: 'Digit5', en: '5', enShift: '%', enCapsShift: '%', enCaps: '5', ru: '5', ruShift: '%', ruCaps: '5'},
    {class: 'keys', keyname: 'Digit6', en: '6', enShift: '^', enCapsShift: '^', enCaps: '6', ru: '6', ruShift: ':', ruCaps: '6'},
    {class: 'keys', keyname: 'Digit7', en: '7', enShift: '&', enCapsShift: '&', enCaps: '7', ru: '7', ruShift: '?', ruCaps: '7'},
    {class: 'keys', keyname: 'Digit8', en: '8', enShift: '*', enCapsShift: '*', enCaps: '8', ru: '8', ruShift: '*', ruCaps: '8'},
    {class: 'keys', keyname: 'Digit9', en: '9', enShift: '(', enCapsShift: '(', enCaps: '9', ru: '9', ruShift: '(', ruCaps: '9'},
    {class: 'keys', keyname: 'Digit0', en: '0', enShift: ')', enCapsShift: ')', enCaps: '0', ru: '0', ruShift: ')', ruCaps: '0'},
    {class: 'keys', keyname: 'Minus', en: '-', enShift: '_', enCapsShift: '_', enCaps: '-', ru: '-', ruShift: '_', ruCaps: '-'},
    {class: 'keys', keyname: 'Equal', en: '=', enShift: '+', enCapsShift: '+', enCaps: '=', ru: '=', ruShift: '+', ruCaps: '='},
    {class: 'keys backspace', keyname: 'Backspace', en: 'Backspace', enShift: 'BackSpace', enCapsShift: 'BackSpace', enCaps: 'Backspace', ru: 'Backspace', ruShift: 'BackSpace', ruCaps: 'Backspace'},
  ],
  [
    {class: 'keys tab', keyname: 'Tab', en: 'Tab', enShift: 'Tab', enCapsShift: 'Tab', enCaps: 'Tab', ru: 'Tab', ruShift: 'Tab', ruCaps: 'Tab'},
    {class: 'keys', keyname: 'KeyQ', en: 'q', enShift: 'Q', enCapsShift: 'q', enCaps: 'Q', ru: 'й', ruShift: 'Й', ruCaps: 'Й'},
    {class: 'keys', keyname: 'KeyW', en: 'w', enShift: 'W', enCapsShift: 'w', enCaps: 'W', ru: 'ц', ruShift: 'Ц', ruCaps: 'Ц'},
    {class: 'keys', keyname: 'KeyE', en: 'e', enShift: 'E', enCapsShift: 'e', enCaps: 'E', ru: 'у', ruShift: 'У', ruCaps: 'У'},
    {class: 'keys', keyname: 'KeyR', en: 'r', enShift: 'R', enCapsShift: 'r', enCaps: 'R', ru: 'к', ruShift: 'К', ruCaps: 'К'},
    {class: 'keys', keyname: 'KeyT', en: 't', enShift: 'T', enCapsShift: 't', enCaps: 'T', ru: 'е', ruShift: 'Е', ruCaps: 'Е'},
    {class: 'keys', keyname: 'KeyY', en: 'y', enShift: 'Y', enCapsShift: 'y', enCaps: 'Y', ru: 'н', ruShift: 'Н', ruCaps: 'Н'},
    {class: 'keys', keyname: 'KeyU', en: 'u', enShift: 'U', enCapsShift: 'u', enCaps: 'U', ru: 'г', ruShift: 'Г', ruCaps: 'Г'},
    {class: 'keys', keyname: 'KeyI', en: 'i', enShift: 'I', enCapsShift: 'i', enCaps: 'I', ru: 'ш', ruShift: 'Ш', ruCaps: 'Ш'},
    {class: 'keys', keyname: 'KeyO', en: 'o', enShift: 'O', enCapsShift: 'o', enCaps: 'O', ru: 'щ', ruShift: 'Щ', ruCaps: 'Щ'},
    {class: 'keys', keyname: 'KeyP', en: 'p', enShift: 'P', enCapsShift: 'p', enCaps: 'P', ru: 'з', ruShift: 'З', ruCaps: 'З'},
    {class: 'keys', keyname: 'BracketLeft', en: '[', enShift: '{', enCapsShift: '{', enCaps: '[', ru: 'х', ruShift: 'Х', ruCaps: 'Х'},
    {class: 'keys', keyname: 'BracketRight', en: ']', enShift: '}', enCapsShift: '}', enCaps: ']', ru: 'ъ', ruShift: 'Ъ', ruCaps: 'Ъ'},
    {class: 'keys slash', keyname: 'Backslash', en: '\\', enShift: '|', enCapsShift: '|', enCaps: '\\', ru: '\\', ruShift: '/', ruCaps: '/'},
  ],
  [
    {class: 'keys caps_lock', keyname: 'CapsLock1', en: 'Caps', enShift: 'Caps', enCapsShift: 'Caps', enCaps: 'Caps', ru: 'Caps', ruShift: 'CAPS', ruCaps: 'Caps'},
    {class: 'keys', keyname: 'KeyA', en: 'a', enShift: 'A', enCapsShift: 'a', enCaps: 'A', ru: 'ф', ruShift: 'Ф', ruCaps: 'Ф'},
    {class: 'keys', keyname: 'KeyS', en: 's', enShift: 'S', enCapsShift: 's', enCaps: 'S', ru: 'ы', ruShift: 'Ы', ruCaps: 'Ы'},
    {class: 'keys', keyname: 'KeyD', en: 'd', enShift: 'D', enCapsShift: 'd', enCaps: 'D', ru: 'в', ruShift: 'В', ruCaps: 'В'},
    {class: 'keys', keyname: 'KeyF', en: 'f', enShift: 'F', enCapsShift: 'f', enCaps: 'F', ru: 'а', ruShift: 'А', ruCaps: 'А'},
    {class: 'keys', keyname: 'KeyG', en: 'g', enShift: 'G', enCapsShift: 'g', enCaps: 'G', ru: 'п', ruShift: 'П', ruCaps: 'П'},
    {class: 'keys', keyname: 'KeyH', en: 'h', enShift: 'H', enCapsShift: 'h', enCaps: 'H', ru: 'р', ruShift: 'Р', ruCaps: 'Р'},
    {class: 'keys', keyname: 'KeyJ', en: 'j', enShift: 'J', enCapsShift: 'j', enCaps: 'J', ru: 'о', ruShift: 'О', ruCaps: 'О'},
    {class: 'keys', keyname: 'KeyK', en: 'k', enShift: 'K', enCapsShift: 'k', enCaps: 'K', ru: 'л', ruShift: 'Л', ruCaps: 'Л'},
    {class: 'keys', keyname: 'KeyL', en: 'l', enShift: 'L', enCapsShift: 'l', enCaps: 'L', ru: 'д', ruShift: 'Д', ruCaps: 'Д'},
    {class: 'keys', keyname: 'Semicolon', en: ';', enShift: ':', enCapsShift: ':', enCaps: ';', ru: 'ж', ruShift: 'Ж', ruCaps: 'Ж'},
    {class: 'keys', keyname: 'Quote', en: '\'', enShift: '"', enCapsShift: '"', enCaps: '\'', ru: 'э', ruShift: 'Э', ruCaps: 'Э'},
    {class: 'keys enter', keyname: 'Enter', en: 'Enter', enShift: 'Enter', enCapsShift: 'Enter', enCaps: 'Enter', ru: 'Enter', ruShift: 'Enter', ruCaps: 'Enter'},
  ],
  [
    {class: 'keys shift_left', keyname: 'ShiftLeft1', en: 'Shift', enShift: 'Shift', enCapsShift: 'Shift', enCaps: 'Shift', ru: 'Shift', ruShift: 'Shift', ruCaps: 'Shift'},
    {class: 'keys', keyname: 'KeyZ', en: 'z', enShift: 'Z', enCapsShift: 'z', enCaps: 'Z', ru: 'я', ruShift: 'Я', ruCaps: 'Я'},
    {class: 'keys', keyname: 'KeyX', en: 'x', enShift: 'X', enCapsShift: 'x', enCaps: 'X', ru: 'ч', ruShift: 'Ч', ruCaps: 'Ч'},
    {class: 'keys', keyname: 'KeyC', en: 'c', enShift: 'C', enCapsShift: 'c', enCaps: 'C', ru: 'с', ruShift: 'С', ruCaps: 'С'},
    {class: 'keys', keyname: 'KeyV', en: 'v', enShift: 'V', enCapsShift: 'v', enCaps: 'V', ru: 'м', ruShift: 'М', ruCaps: 'М'},
    {class: 'keys', keyname: 'KeyB', en: 'b', enShift: 'B', enCapsShift: 'b', enCaps: 'B', ru: 'и', ruShift: 'И', ruCaps: 'И'},
    {class: 'keys', keyname: 'KeyN', en: 'n', enShift: 'N', enCapsShift: 'n', enCaps: 'N', ru: 'т', ruShift: 'Т', ruCaps: 'Т'},
    {class: 'keys', keyname: 'KeyM', en: 'm', enShift: 'M', enCapsShift: 'm', enCaps: 'M', ru: 'ь', ruShift: 'Ь', ruCaps: 'Ь'},
    {class: 'keys', keyname: 'Comma', en: ',', enShift: '<', enCapsShift: '<', enCaps: ',', ru: 'б', ruShift: 'Б', ruCaps: 'Б'},
    {class: 'keys', keyname: 'Period', en: '.', enShift: '>', enCapsShift: '>', enCaps: '.', ru: 'ю', ruShift: 'Ю', ruCaps: 'Ю'},
    {class: 'keys', keyname: 'Slash', en: '/', enShift: '?', enCapsShift: '?', enCaps: '/', ru: '.', ruShift: ',', ruCaps: ','},
    {class: 'keys shift_right', keyname: 'ShiftRight', en: 'Shift', enShift: 'Shift', enCapsShift: 'Shift', enCaps: 'Shift', ru: 'Shift', ruShift: 'Shift', ruCaps: 'Shift'},
  ],
  [
    {class: 'keys', keyname: 'ControlLeft', en: 'Ctrl', enShift: 'Ctrl', enCapsShift: 'Ctrl', enCaps: 'Ctrl', ru: 'Ctrl', ruShift: 'Ctrl', ruCaps: 'Ctrl'},
    {class: 'keys os_left', keyname: 'OSLeft', en: 'Win', enShift: 'Win', enCapsShift: 'Win', enCaps: 'Win', ru: 'Win', ruShift: 'Win', ruCaps: 'Win'},
    {class: 'keys', keyname: 'AltLeft', en: 'Alt', enShift: 'Alt', enCapsShift: 'Alt', enCaps: 'Alt', ru: 'Alt', ruShift: 'Alt', ruCaps: 'Alt'},
    {class: 'keys space', keyname: 'Space', en: 'Space', enShift: 'Space', enCapsShift: 'Space', enCaps: 'Space', ru: 'Space', ruShift: 'Space', ruCaps: 'Space'},
    {class: 'keys', keyname: 'AltRight', en: 'Alt', enShift: 'Alt', enCapsShift: 'Alt', enCaps: 'Alt', ru: 'Alt', ruShift: 'Alt', ruCaps: 'Alt'},
    {class: 'keys', keyname: 'ControlRight', en: 'Ctrl', enShift: 'Ctrl', enCapsShift: 'Ctrl', enCaps: 'Ctrl', ru: 'Ctrl', ruShift: 'Ctrld', ruCaps: 'Ctrl'},
    {class: 'keys', keyname: 'ArrowLeft', en: '←', enShift: '←', enCapsShift: '←', enCaps: '←', ru: '←', ruShift: '←', ruCaps: '←'},
    {class: 'keys', keyname: 'ArrowUp', en: '↑', enShift: '↑', enCapsShift: '↑', enCaps: '↑', ru: '↑', ruShift: '↑', ruCaps: '↑'},
    {class: 'keys', keyname: 'ArrowDown', en: '→', enShift: '→', enCapsShift: '→', enCaps: '→', ru: '→', ruShift: '→', ruCaps: '→'},
    {class: 'keys', keyname: 'ArrowRight', en: '↓', enShift: '↓', enCapsShift: '↓', enCaps: '↓', ru: '↓', ruShift: '↓', ruCaps: '↓'},
  ],
];
